import Head from 'next/head'
import Side from '@/components/Side'

export default function Home() {
  return (
    <>
      <Head>
        <title>Storage Malik Brand</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Side />
    </>
  )
}
